language: node_js
node_js:
- lts/boron
- node
after_script: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: ZuQSGmtOq56xmHVS9hvVO3YYHucyptPP2tffHXe3VaI11XfGjbg/qWW+x+r9607KlmBLD4RUjBX0miGtfcKqQEjs5Zz0wROaCVPXIYT4ySbg4Usy8mK0pbKpF00XgaTc8hnVJdI90LCmchSjuQouHAZFV/SWS8o1xKntnvvs74qck+XFD9NDbzd3UyamoVD4wSoblatH1p2oofT1ywJD3XT33h6p9JNMs68vKip4F5oXBAWTvLW3a7s9x/UQsZ8N3n+xWUCWXmWbVOPY6vG+OjZOkmk6rNf+lQSyCOpPO0h3LXWVQrp7elu9r8VHZrqG7l702lWkufw0O8O+jvWsB4V7cE3g9wkwYYGoMJ4z9Wc6jWWKog4bKh1fFNkfxgKWvUmXrWGxYuM6d5AxuNac3IEM3sDoVa+Hmdn7pjxIUGGHARfhi4vxv76kKGjVggNXS/pKmVYx6sviGjHy/dVt8RaE++sd7NglSvXbfjDwYvfiF5OiAgl9z7bXaKAVXdO3b28UuPRTv8oRsL+StpLx7MvkFbwNLRAR0PAyH2QjVgk1S8l/2gbmkayCv6+n8cqsa5wjpaOWhDjmCB8d3AEUgWOw9agDfolQeXqA17ed4/DL1pCDNE1fvQmd0wRWzOpx85FriM2oTKKQ9T2EMWEIdoNs4aqE0X61YaFkhBB48cA=
  file:
    - "hast-util-phrasing.js"
    - "hast-util-phrasing.min.js"
  on:
    tags: true
