language: node_js
node_js:
- '4.0'
- '9.0'
after_script: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: iapBIHL+6QAOV3ow4FijnSIgbA5WUfXoEJo99BB18VA6iVqYXLg/ByImlbcgLB9hytQcHmwZF+jSh+R02O8OdzHEHrxKZM23+I3bbNaQ+56/VBbTNSqJDs0BCnzcosfoBUY7FCrcSORbI9o8atmFOlAe7CP1nNQ9RoUbo/ng2VyJh/eQ/vf5vGcRVkCBGDjLisp3Xb6Wd/OPAedL3+nT/G2P8AWLCmGbLagUHHIqYR9QhTK8ffx63+dldDndetDwVZl+/5GWl4cweukFl5BLBcth7qxNVkMJ6kqU2N0Px8lSJ771/p4P01Yht5K3Xe1kSoUGf25BrJjYWZl9VlarhqSC4SQA38DivqMj1ytEjAnTXMuaFVvTvuVrjMei1PiuA5rK9VDkyVb/KpsPGr3EvB+4NPm28EavXnLQHRZNNHXF0n2/jL74qqAGUJ2m8B7Wy7ez0yO3Beow5MgMVIfHaLEXNqBZlzRHe5X6+kos4yiYvbrKLkNqNPPquq14aHNW8aNeTBrrssC364o2zzKbQTjtfY0hKs1wUWA7XgxjoOsxCFfH4wpAc2Up5bMV3BvWAGD+3bb+6hqpxsWL47hca5YKgHgeIaan6c+upGvJkUyiHetcIbpEqXuQKXljS0XJ4czeFXgp4xsBcZmOQ5OOPLPV1NaahwBC3MAbsF55smY=
  file:
    - "hast-util-phrasing.js"
    - "hast-util-phrasing.min.js"
  on:
    tags: true
    node: '9.0'
